FROM docker.io/library/golang:1.26.0-bookworm AS build

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    make \
    build-essential \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/app
COPY . .

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

RUN make miniflux-no-pie

FROM docker.io/library/alpine:3.23

LABEL org.opencontainers.image.title=Miniflux
LABEL org.opencontainers.image.description="Miniflux is a minimalist and opinionated feed reader"
LABEL org.opencontainers.image.vendor="Frédéric Guillot"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.url=https://miniflux.app
LABEL org.opencontainers.image.source=https://github.com/miniflux/v2
LABEL org.opencontainers.image.documentation=https://miniflux.app/docs/

EXPOSE 8080

ENV LISTEN_ADDR=0.0.0.0:8080 \
    DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable \
    RUN_MIGRATIONS=1 \
    LOG_LEVEL=info \
    LOG_FORMAT=text \
    LOG_FILE=stderr \
    WATCHDOG=1

RUN apk add --no-cache ca-certificates tzdata \
  && addgroup -S nonroot \
  && adduser -S -D -H -G nonroot nonroot

COPY --from=build /go/src/app/miniflux /usr/bin/miniflux
WORKDIR /usr/bin

USER 65534:65534
CMD ["/usr/bin/miniflux"]
